def menus():
    menus=  [
        {"name": "고기 새우 아보카도 덮밥", "calories": 760},
        {"name": "와사비마요 목살 덮밥", "calories": 420},
        {"name": "불고기 나물 비빔밥", "calories": 520},
        {"name": "치즈 바질 파스타", "calories": 450},
        {"name": "스테이크 샐러드", "calories": 345},
        {"name": "아보카도 새우 콩피 샐러드", "calories": 280},
        {"name": "마라 건두부 볶음", "calories": 570},
        {"name": "그릭요거트 볼", "calories": 570},
        {"name": "이뮨킥", "calories": 200},
        {"name": "단백질부스트업", "calories": 245},
        {"name": "샐러드 콥샐러드", "calories": 300},
        {"name": "김치 새우볶음밥", "calories": 430},
        {"name": "오므라이스", "calories": 550},
        {"name": "참치 샐러드롤", "calories": 380},
        {"name": "토마토 스파게티", "calories": 400},
        {"name": "고구마 치즈 그라탕", "calories": 480},
        {"name": "두부 퀴노아 샐러드", "calories": 350},
        {"name": "닭가슴살 샐러드", "calories": 320},
        {"name": "비프 스테이크", "calories": 600},
        {"name": "미니 버거 콤보", "calories": 750},
        {"name": "소고기 유니짜장", "calories": 680},
        {"name": "포테이토 김치볶음밥", "calories": 610},
        {"name": "단호박 바질 크림파스타", "calories": 430},
        {"name": "레몬 새우 샐러드", "calories": 360},
        {"name": "마라 치킨볼", "calories": 480},
        {"name": "요거트 복숭아 그라니타", "calories": 180},
        {"name": "칠리 닭가슴살 샐러드", "calories": 420},
        {"name": "소고기 스테이크", "calories": 800},
        {"name": "냉우동", "calories": 320},
        {"name": "골뱅이소면", "calories": 470},
        {"name": "오트밀 블루베리 스무디", "calories": 280},
        {"name": "카레 퀴노아 볼", "calories": 540},
        {"name": "미트볼 포케", "calories": 650},
        {"name": "연어 아보카도 샐러드", "calories": 450},
        {"name": "오징어 미역국", "calories": 310},
        {"name": "닭고기 샐러드", "calories": 280},
        {"name": "랍스타 샐러드", "calories": 490},
        {"name": "불고기 버리또", "calories": 720},
        {"name": "낙지 카레소바", "calories": 520},
        {"name": "베이컨 감자볶음", "calories": 550},
        {"name": "크레이프", "calories": 420},
        {"name": "가지 볶음", "calories": 300},
        {"name": "콩나물 비빔밥", "calories": 480},
        {"name": "멸치 볶음", "calories": 330},
        {"name": "흑임자 파운드케이크", "calories": 290},
        {"name": "치즈 돈까스", "calories": 540},
        {"name": "만두 미소국수", "calories": 400},
        {"name": "멸치 크림파스타", "calories": 490},
        {"name": "연어 감자 샐러드", "calories": 390},
        {"name": "소시지 바게트", "calories": 460},
        {"name": "버섯 크림수프", "calories": 230},
        {"name": "훈제 연어 샌드위치", "calories": 600},
        {"name": "파니니", "calories": 480},
        {"name": "양송이 크림파스타", "calories": 470},
        {"name": "우유 주먹밥", "calories": 380},
        {"name": "닭가슴살 크림파스타", "calories": 580},
        {"name": "메론 마카롱", "calories": 280},
        {"name": "해물 카레소바", "calories": 570},
        {"name": "새우 볶음밥", "calories": 490},
        {"name": "돼지갈비찜", "calories": 540},
        {"name": "감자채볶음", "calories": 420},
        {"name": "초밥", "calories": 700},
        {"name": "비프소시지 구이", "calories": 600},
        {"name": "오이 겉절이", "calories": 50},
        {"name": "차슈 도시락", "calories": 790},
        {"name": "크림스프 스위트치즈", "calories": 350},
        {"name": "해물 볶음", "calories": 290},
        {"name": "새우마요 버거", "calories": 550},
        {"name": "부추 고추장찌개", "calories": 320},
        {"name": "어묵 장조림", "calories": 210},
        {"name": "사과 마카롱", "calories": 330},
        {"name": "꽁치 감자찌개", "calories": 270},
        {"name": "새우 버터 간장", "calories": 370},
        {"name": "배 샌드위치", "calories": 390},
        {"name": "두부 크림수프", "calories": 210},
        {"name": "떡볶이 샐러드", "calories": 470},
        {"name": "소시지야채볶음", "calories": 320},
        {"name": "피자핫도그", "calories": 590},
        {"name": "꼬막 비빔밥", "calories": 540},
        {"name": "무우 샐러드", "calories": 230},
        {"name": "치킨마요 샌드위치", "calories": 570},
        {"name": "닭가슴살 채소볶음", "calories": 400},
        {"name": "비프샐러드", "calories": 330},
        {"name": "페퍼로니 피자", "calories": 800},
        {"name": "부대찌개", "calories": 680},
        {"name": "버섯 크림파스타", "calories": 540},
        {"name": "마카롱", "calories": 430},
        {"name": "갈비찜", "calories": 590},
        {"name": "해물라면", "calories": 510},
        {"name": "버섯라자냐", "calories": 650},
        {"name": "미니크로와상", "calories": 420},
        {"name": "가래떡볶이", "calories": 600},
        {"name": "오믈렛밥", "calories": 530},
        {"name": "새우튀김", "calories": 380},
        {"name": "버섯볶음밥", "calories": 460},
        {"name": "참치마요덮밥", "calories": 750},
        {"name": "김치찌개", "calories": 290},
        {"name": "양배추쌈밥", "calories": 330},
        {"name": "참치김밥", "calories": 300},
        {"name": "새우 샐러드", "calories": 270},
        {"name": "해물누룽지탕", "calories": 490},
        {"name": "닭가슴살 샌드위치", "calories": 590},
        {"name": "꼬막무침", "calories": 130},
        {"name": "골뱅이무침", "calories": 170},
        {"name": "아보카도 샐러드", "calories": 210},
        {"name": "김치볶음밥", "calories": 550},
        {"name": "메로주먹밥", "calories": 480},
        {"name": "닭갈비", "calories": 700},
        {"name": "야채튀김", "calories": 270},
        {"name": "백숙", "calories": 800},
        {"name": "해물탕", "calories": 460},
        {"name": "장어구이", "calories": 790},
        {"name": "고등어조림", "calories": 420},
        {"name": "부타동", "calories": 650},
        {"name": "고구마마카롱", "calories": 360},
        {"name": "햄치즈버거", "calories": 560},
        {"name": "새우튀김초밥", "calories": 540},
        {"name": "철판버섯덮밥", "calories": 500},
        {"name": "스팸마요덮밥", "calories": 710},
        {"name": "비프스튜", "calories": 590},
        {"name": "치즈불닭덮밥", "calories": 550},
        {"name": "누룽지탕", "calories": 420},
        {"name": "크래미 김치찌개", "calories": 400},
        {"name": "잔치국수", "calories": 490},
        {"name": "로제스파게티", "calories": 660},
        {"name": "부대찌개 덮밥", "calories": 740},
        {"name": "미트스파게티", "calories": 600},
        {"name": "라따뚜이 컵밥", "calories": 420},
        {"name": "김치치즈볶음밥", "calories": 560},
        {"name": "새우볶음밥", "calories": 470},
        {"name": "햄에그샌드위치", "calories": 520},
        {"name": "마파두부덮밥", "calories": 580},
        {"name": "오므라이스버거", "calories": 620},
        {"name": "연어크림파스타", "calories": 670},
        {"name": "오코노미야끼", "calories": 650},
        {"name": "치킨마요 덮밥", "calories": 780},
        {"name": "냉모밀", "calories": 380},
        {"name": "양념치킨버거", "calories": 660},
        {"name": "돈가스김밥", "calories": 450},
        {"name": "토마토스파게티", "calories": 560},
        {"name": "떡국", "calories": 330},
        {"name": "비빔국수", "calories": 390},
        {"name": "햄치즈돈까스", "calories": 600},
        {"name": "아시아 왕교자", "calories": 480},
        {"name": "돼지갈비구이", "calories": 640},
        {"name": "갈릭버터새우", "calories": 480},
        {"name": "갈비살김치찌개", "calories": 450},
        {"name": "장어덮밥", "calories": 700},
        {"name": "올리브차돌박이", "calories": 560},
        {"name": "배터죽", "calories": 330},
        {"name": "반숙달걀크로크마담", "calories": 620},
        {"name": "차슈김치찌개", "calories": 440},
        {"name": "짜장라면", "calories": 570},
        {"name": "크래미크림스튜", "calories": 620},
        {"name": "햄치즈케밥", "calories": 430},
        {"name": "두부와 사과", "calories": 260},
        {"name": "김치날치알볶음밥", "calories": 550},
        {"name": "낙지볶음밥", "calories": 590},
        {"name": "돈까스카레", "calories": 670},
        {"name": "치킨마요덮밥", "calories": 780},
        {"name": "닭볶음탕", "calories": 700},
        {"name": "청국장", "calories": 360},
        {"name": "스테이크야끼소바", "calories": 540},
        {"name": "콩나물국밥", "calories": 330},
        {"name": "미트볼호밀스파게티", "calories": 580},
        {"name": "파채샌드위치", "calories": 560},
        {"name": "고등어조림덮밥", "calories": 730},
        {"name": "닭가슴살크림스튜", "calories": 630},
        {"name": "로제떡볶이", "calories": 550},
        {"name": "오이샐러드", "calories": 80},
        {"name": "한우육개장", "calories": 410},
        {"name": "크래미후라이드치킨", "calories": 540},
        {"name": "허니버터칩크림스튜", "calories": 580},
        {"name": "완두콩국", "calories": 270},
        {"name": "부대죽", "calories": 440},
        {"name": "꽃빵호떡", "calories": 290},
        {"name": "팥빙수", "calories": 470},
        {"name": "돈카츠동", "calories": 540},
        {"name": "김치말이국수", "calories": 340},
        {"name": "짜장우동", "calories": 570},
        {"name": "육개장", "calories": 350},
        {"name": "크랩커틀릿", "calories": 440},
        {"name": "라볶이", "calories": 510},
        {"name": "치즈라면", "calories": 450},
        {"name": "돈카츠김밥", "calories": 440},
        {"name": "꼬막비빔국수", "calories": 340},
        {"name": "무말랭이김치", "calories": 40},
        {"name": "닭가슴살요리조리샐러드", "calories": 260},
        {"name": "김치볶음우동", "calories": 480},
        {"name": "김치밥", "calories": 460},
        {"name": "파인애플밥", "calories": 390},
        {"name": "흰밥", "calories": 380},
        {"name": "소세지야채볶음", "calories": 380},
        {"name": "콩국수", "calories": 330},
        {"name": "아라비아따뚜이", "calories": 400},
        {"name": "계란라면", "calories": 380},
        {"name": "브로콜리김치볶음밥", "calories": 420},
        {"name": "새우볶음밥볶음", "calories": 500},
        {"name": "떡국라면", "calories": 430},
        {"name": "해물볶음밥", "calories": 490},
        {"name": "김치전", "calories": 400},
        {"name": "스팸마요덮밥", "calories": 660},
        {"name": "유부버거", "calories": 420},
        {"name": "고구마스콘", "calories": 200},
        {"name": "짜장밥", "calories": 490},
        {"name": "삼치조림", "calories": 510},
        {"name": "두부크림스튜", "calories": 320},
        {"name": "오므라이스치킨", "calories": 980},
        {"name": "참치크림스튜", "calories": 600},
        {"name": "냉우동볶음", "calories": 900},
        {"name": "새우알찹쌀탕수육", "calories": 850},
        {"name": "낙지볶음", "calories": 580},
        {"name": "미니호떡", "calories": 1000},
        {"name": "닭고기칼국수", "calories": 750},
        {"name": "새우튀김죽", "calories": 480},
        {"name": "제육덮밥", "calories": 580},
        {"name": "날치알초밥", "calories": 500},
        {"name": "꼬막찜", "calories": 1050},
        {"name": "매운마늘치킨", "calories": 1200},
        {"name": "치킨커리라이스", "calories": 1150},
        {"name": "무쌈샐러드", "calories": 80},
        {"name": "미트소스스파게티", "calories": 590},
        {"name": "잔치국수말이", "calories": 440},
        {"name": "김치짜장", "calories": 640},
        {"name": "오징어볶음밥", "calories": 560},
        {"name": "해물볶음밥", "calories": 490},
        {"name": "팔보채", "calories": 170},
        {"name": "오이냉국", "calories": 110},
        {"name": "오꼬노미야끼", "calories": 640},
        {"name": "치킨까스", "calories": 600},
        {"name": "스팸마요덮밥", "calories": 720},
        {"name": "소불고기덮밥", "calories": 720},
        {"name": "햄에그샌드위치", "calories": 540},
        {"name": "차돌박이구이", "calories": 740},
        {"name": "닭데리야끼", "calories": 580},
        {"name": "잔치국수", "calories": 510},
        {"name": "매운양념치킨", "calories": 610},
        {"name": "연어덮밥", "calories": 660},
        {"name": "냉모밀", "calories": 380},
        {"name": "닭볶음탕", "calories": 700},
        {"name": "소세지야채볶음", "calories": 380},
        {"name": "비빔국수", "calories": 390},
        {"name": "콩나물국밥", "calories": 330},
        {"name": "계란라면", "calories": 380},
        {"name": "김치날치알볶음밥", "calories": 550},
        {"name": "낙지볶음밥", "calories": 590},
        {"name": "해물볶음밥", "calories": 490},
        {"name": "김치전", "calories": 400},
        {"name": "삼치조림", "calories": 510},
        {"name": "두부크림스튜", "calories": 320},
        {"name": "참치크림스튜", "calories": 600},
        {"name": "미니호떡", "calories": 310},
        {"name": "새우튀김죽", "calories": 480},
        {"name": "제육덮밥", "calories": 580},
        {"name": "매운마늘치킨", "calories": 610},
        {"name": "치킨커리라이스", "calories": 720},
        {"name": "무쌈샐러드", "calories": 80},
        {"name": "미트소스스파게티", "calories": 590},
        {"name": "잔치국수말이", "calories": 440},
        {"name": "오이냉국", "calories": 110},
        {"name": "김치짜장", "calories": 640},
        {"name": "오징어볶음밥", "calories": 560},
        {"name": "해물볶음밥", "calories": 490},
        {"name": "팔보채", "calories": 170},
        {"name": "오꼬노미야끼", "calories": 640},
        {"name": "치킨까스", "calories": 600},
        {"name": "소불고기덮밥", "calories": 720},
        {"name": "스팸마요덮밥", "calories": 720},
        {"name": "햄에그샌드위치", "calories": 540},
        {"name": "차돌박이구이", "calories": 740},
        {"name": "닭데리야끼", "calories": 580},
        {"name": "잔치국수", "calories": 510},
        {"name": "매운양념치킨", "calories": 610},
        {"name": "연어덮밥", "calories": 660},
        {"name": "냉모밀", "calories": 380},
        {"name": "닭볶음탕", "calories": 700},
        {"name": "소세지야채볶음", "calories": 380},
        {"name": "비빔국수", "calories": 390},
        {"name": "콩나물국밥", "calories": 330},
        {"name": "계란라면", "calories": 380},
        {"name": "김치날치알볶음밥", "calories": 550},
        {"name": "낙지볶음밥", "calories": 590},
        {"name": "해물볶음밥", "calories": 490},
        {"name": "김치전", "calories": 400},
        {"name": "삼치조림", "calories": 510},
        {"name": "두부크림스튜", "calories": 320},
        {"name": "참치크림스튜", "calories": 600},
        {"name": "미니호떡", "calories": 310},
        {"name": "새우튀김죽", "calories": 480},
        {"name": "제육덮밥", "calories": 580},
        {"name": "매운마늘치킨", "calories": 610},
        {"name": "치킨커리라이스", "calories": 720},
        {"name": "무쌈샐러드", "calories": 80},
        {"name": "미트소스스파게티", "calories": 590},
        {"name": "잔치국수말이", "calories": 440},
        {"name": "오이냉국", "calories": 110},
        {"name": "김치짜장", "calories": 640},
        {"name": "오징어볶음밥", "calories": 560},
        {"name": "해물볶음밥", "calories": 490},
        {"name": "팔보채", "calories": 170},
        {"name": "오꼬노미야끼", "calories": 640},
        {"name": "치킨까스", "calories": 600},
        {"name": "소불고기덮밥", "calories": 720},
        {"name": "스팸마요덮밥", "calories": 720},
        {"name": "햄에그샌드위치", "calories": 540},
        {"name": "차돌박이구이", "calories": 740},
        {"name": "닭데리야끼", "calories": 580},
        {"name": "잔치국수", "calories": 510},
        {"name": "매운양념치킨", "calories": 610},
        {"name": "연어덮밥", "calories": 660},
        {"name": "냉모밀", "calories": 380},
        {"name": "닭볶음탕", "calories": 700},
        {"name": "소세지야채볶음", "calories": 380},
        {"name": "비빔국수", "calories": 390},
        {"name": "콩나물국밥", "calories": 330},
        {"name": "계란라면", "calories": 380},
        {"name": "김치날치알볶음밥", "calories": 550},
        {"name": "낙지볶음밥", "calories": 590},
        {"name": "해물볶음밥", "calories": 490},
        {"name": "김치전", "calories": 400},
        {"name": "삼치조림", "calories": 510},
        {"name": "두부크림스튜", "calories": 320}
    ]
    return menus
